name: My First Workflow
# on: push
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: true
        default: 'On-demand testing'

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Welcome message
        run: echo "My first GitHub Actions Job"
      - name: List files
        run: ls
      - name: Read file
        run: cat README.md